<a href="https://colab.research.google.com/github/Nikita785/BLCMods/blob/master/day3_cocojambo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
import pandas as pd

df_fd = pd.read_csv('/content/financial_data.csv')
df_pr = pd.read_csv('/content/prolongations.csv')

In [87]:
#  Шаг первый: очистка данных

  # df_fd

#    - Удалил столбец "Причины дубля" из df_fd
df_fd = df_fd.drop('Причина дубля', axis=1)

#    - Преобразовал месяцы в df_fd в числовой тип и заполнил NaN нулями
df_fd_dt = ['id', 'Account']

for col in df_fd.columns:
  if col not in df_fd_dt:
    df_fd[col] = pd.to_numeric(df_fd[col], errors='coerce').fillna(0)

#     - Преобразовал названия столбцов с месяцами на английский

month_translation = {
    'Январь': 'January',
    'Февраль': 'February',
    'Март': 'March',
    'Апрель': 'April',
    'Май': 'May',
    'Июнь': 'June',
    'Июль': 'July',
    'Август': 'August',
    'Сентябрь': 'September',
    'Октябрь': 'October',
    'Ноябрь': 'November',
    'Декабрь': 'December'
}

for col in df_fd.columns:
    month_name_parts = col.split()
    if len(month_name_parts) > 1 and month_name_parts[0] in month_translation:
        new_col = month_translation[month_name_parts[0]] + ' ' + month_name_parts[1]
        df_fd.rename(columns={col: new_col}, inplace=True)

  # df_pr
month_translation_dr = {
    'январь': 'January',
    'февраль': 'February',
    'март': 'March',
    'апрель': 'April',
    'май': 'May',
    'июнь': 'June',
    'июль': 'July',
    'август': 'August',
    'сентябрь': 'September',
    'октябрь': 'October',
    'ноябрь': 'November',
    'декабрь': 'December'
}

#Переименовал столбцы
df_pr.rename(columns={'AM': 'Account', 'month': 'Month'} inplace=True)

#Преобразовал значения столбца
for value in df['Month']:
  value_parts = value.split()
  if len(value_parts) > 1 and value_parts[0] in month_translation_dr:
        new_val = month_translation[month_name_parts[0]] + ' ' + month_name_parts[1]
        df_fd.rename(columns={col: new_col}, inplace=True)

In [96]:
df_pr

       id         month                             AM
0      42   ноябрь 2022   Васильев Артем Александрович
1     453   ноябрь 2022   Васильев Артем Александрович
2     548   ноябрь 2022      Михайлов Андрей Сергеевич
3      87   ноябрь 2022  Соколова Анастасия Викторовна
4     429   ноябрь 2022  Соколова Анастасия Викторовна
..    ...           ...                            ...
472   955  декабрь 2023    Смирнова Ольга Владимировна
473  1004  декабрь 2023                        без А/М
474   281  декабрь 2023  Соколова Анастасия Викторовна
475   785  декабрь 2023  Соколова Анастасия Викторовна
476   913  декабрь 2023    Смирнова Ольга Владимировна

[477 rows x 3 columns]

In [89]:
# Шаг второй: объединение таблиц для произведения расчётов


df_merge = pd.merge(df_fd, df_pr, on=['id', '', how='left')

In [ ]:
df_merge = pd.merge(df_fd, df_pr, on=['id'])

In [97]:
df_fd.columns

Index(['id', 'November 2022', 'December 2022', 'January 2023', 'February 2023',
       'March 2023', 'April 2023', 'May 2023', 'June 2023', 'July 2023',
       'August 2023', 'September 2023', 'October 2023', 'November 2023',
       'December 2023', 'January 2024', 'February 2024', 'Account'],
      dtype='object')

In [92]:
df_pr

       id         month                             AM
0      42   ноябрь 2022   Васильев Артем Александрович
1     453   ноябрь 2022   Васильев Артем Александрович
2     548   ноябрь 2022      Михайлов Андрей Сергеевич
3      87   ноябрь 2022  Соколова Анастасия Викторовна
4     429   ноябрь 2022  Соколова Анастасия Викторовна
..    ...           ...                            ...
472   955  декабрь 2023    Смирнова Ольга Владимировна
473  1004  декабрь 2023                        без А/М
474   281  декабрь 2023  Соколова Анастасия Викторовна
475   785  декабрь 2023  Соколова Анастасия Викторовна
476   913  декабрь 2023    Смирнова Ольга Владимировна

[477 rows x 3 columns]

In [90]:
df_merge

,id,November 2022,December 2022,January 2023,February 2023,March 2023,April 2023,May 2023,June 2023,July 2023,August 2023,September 2023,October 2023,November 2023,December 2023,January 2024,February 2024,Account,month,AM
0,42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Васильев Артем Александрович,ноябрь 2022,Васильев Артем Александрович
1,657,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Васильев Артем Александрович,ноябрь 2022,Васильев Артем Александрович
2,657,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Васильев Артем Александрович,ноябрь 2022,Васильев Артем Александрович
3,594,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Васильев Артем Александрович,ноябрь 2022,Васильев Артем Александрович
4,665,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Васильев Артем Александрович,ноябрь 2022,Васильев Артем Александрович
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,281,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Соколова Анастасия Викторовна,декабрь 2023,Соколова Анастасия Викторовна
722,785,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Соколова Анастасия Викторовна,февраль 2023,Михайлов Андрей Сергеевич
723,785,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Соколова Анастасия Викторовна,декабрь 2023,Соколова Анастасия Викторовна
724,913,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Смирнова Ольга Владимировна,декабрь 2023,Смирнова Ольга Владимировна
725,930,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Кузнецов Михаил Иванович,NaN,NaN

In [42]:
import pandas as pd

def calculate_retention(df, month, lag):
    """
    Рассчитывает коэффициент пролонгации.

    Args:
        df: Датафрейм с данными.
        month: Месяц, для которого рассчитывается коэффициент (в формате datetime).
        lag: 1 - для расчета коэффициента для пролонгаций в первый месяц, 2 - для второй месяц.

    Returns:
        Коэффициент пролонгации (float).
    """

    end_month = pd.to_datetime(month)  #Убедимся, что формат даты
    month_name = end_month.strftime('%B %Y').lower() #Приводим к нужному формату названия месяца
    # Фильтруем проекты, завершившиеся в указанном месяце
    df_ended = df[df['month'] == end_month]

    # Определяем месяц пролонгации (в зависимости от lag)
    prolongation_month = end_month + pd.DateOffset(months=lag)
    prolongation_month_name = prolongation_month.strftime('%B %Y').lower()

    # Фильтруем проекты, пролонгированные в следующем месяце
    #df_prolonged = df[df['month'] == end_month]
    df_prolonged = df_ended[df_ended[prolongation_month_name] > 0]


    # Рассчитываем суммы отгрузок
    total_ended_value = df_ended[month_name].sum()
    total_prolonged_value = df_prolonged[prolongation_month_name].sum()

    # Рассчитываем коэффициент пролонгации
    if total_ended_value > 0:
        retention_rate = total_prolonged_value / total_ended_value
    else:
        retention_rate = 0  # Избегаем деления на ноль

    return retention_rate

In [ ]:
def calc_coef(df, target_year):

In [52]:


df_merge['month'] = pd.to_datetime(df_merge['month'], format='%B %Y', locale='ru_RU')

TypeError: to_datetime() got an unexpected keyword argument 'locale'

In [46]:

import pandas as pd

# Загрузка данных
try:
    prolongations = pd.read_csv('prolongations.csv')
    financial_data = pd.read_csv('financial_data.csv')
except FileNotFoundError:
    print("Ошибка: Убедитесь, что файлы 'prolongations.csv' и 'financial_data.csv' находятся в той же директории, что и этот скрипт.")
    exit()

# Предобработка данных

# 1.1. Приведение названий столбцов к общему виду (нижний регистр, snake_case)
def rename_columns(df):
    new_columns = {col: col.lower().replace(" ", "_") for col in df.columns}
    return df.rename(columns=new_columns)

prolongations = rename_columns(prolongations)
financial_data = rename_columns(financial_data)

# 1.2. Удаление дубликатов в financial_data (важно выбрать стратегию!)
# Предпологаю, что дубли возникают из-за разных причин ("причина_дубля"), и нам нужна агрегация
# по id и месяцу.  В данном примере суммируем отгрузки по месяцам.  Можно выбрать другую стратегию,
# например, брать первое значение, если это не денежные показатели.
financial_data = financial_data.groupby('id').sum().reset_index()
financial_data = financial_data.drop('причина_дубля', axis=1, errors='ignore')

# 1.3.  Преобразование данных о месяцах в financial_data из широкого формата в длинный (melt)
month_cols = [col for col in financial_data.columns if col not in ['id', 'account']]  # Динамическое определение столбцов с месяцами
financial_data_melted = pd.melt(financial_data,
                                id_vars=['id', 'account'],
                                value_vars=month_cols,
                                var_name='month',
                                value_name='отгрузка')

# 1.4 Преобразование столбца 'month' к типу datetime
financial_data_melted['month'] = pd.to_datetime(financial_data_melted['month'], format='%B', errors='coerce').dt.month
financial_data_melted['month'] = financial_data_melted['month'].fillna(0).astype(int)

# Добавляем год к месяцу (предполагаем, что все данные за 2023 год)
financial_data_melted['year'] = 2023
financial_data_melted['month'] = financial_data_melted['month'].astype(str)
financial_data_melted['year'] = financial_data_melted['year'].astype(str)
financial_data_melted['date'] = financial_data_melted['year'] + '-' + financial_data_melted['month']
financial_data_melted = financial_data_melted.drop(['month', 'year'], axis=1)
financial_data_melted = financial_data_melted.rename(columns={'date': 'month'})
financial_data_melted['month'] = pd.to_datetime(financial_data_melted['month'])
financial_data_melted = financial_data_melted.rename(columns={'account': 'am'})

# 1.5. Объединение данных
# Объединяем prolongations и financial_data_melted
df = pd.merge(prolongations, financial_data_melted, on='id', how='left')

# 1.6. Удаляем строки без информации об отгрузке.
df = df.dropna(subset=['отгрузка'])

# 1.7. Создание столбца с датой последнего месяца реализации проекта
df['last_month_end'] = pd.to_datetime(df['month'], format='%Y-%m-%d')

# Расчет коэффициентов пролонгации

def calculate_renewal_rates(df, target_year=2023):
    """
    Рассчитывает коэффициенты пролонгации для каждого менеджера и для всего отдела в целом:
    1.  За каждый месяц
    2.  За год

    Args:
        df: DataFrame с данными о проектах и отгрузках.
        target_year: Год, за который нужно рассчитать коэффициенты.

    Returns:
        DataFrame с коэффициентами пролонгации.
    """

    results = []
    all_managers = df['am'].unique().tolist()  # Список всех менеджеров
    all_managers.append('all')  # Добавляем 'all' для расчета по всему отделу

    for manager in all_managers:  # Итерируемся по каждому менеджеру (и "всем")
        for month in range(1, 13):  # Проходим по всем месяцам (1-12)

            # Фильтруем данные для текущего месяца и года.
            if manager == 'all':
                df_month = df[(df['last_month_end'].dt.year == target_year) & ((df['last_month_end'].dt.month + 1 == month) | (df['last_month_end'].dt.month + 2 == month))]
            else:
                df_month = df[(df['am'] == manager) & (df['last_month_end'].dt.year == target_year) & ((df['last_month_end'].dt.month + 1 == month) | (df['last_month_end'].dt.month + 2 == month))]

            # Рассчитываем коэффициент пролонгации для первого месяца.
            df_month_1 = df_month[df_month['last_month_end'].dt.month + 1 == month]
            total_last_month_1 = df_month_1.groupby('id')['отгрузка'].sum().sum()
            df_month_1_renewed = df_month_1[df_month_1['month'].dt.month == month]
            total_renewed_month_1 = df_month_1_renewed.groupby('id')['отгрузка'].sum().sum()
            renewal_rate_month_1 = total_renewed_month_1 / total_last_month_1 if total_last_month_1 > 0 else 0

            # Рассчитываем коэффициент пролонгации для второго месяца.
            df_month_2 = df_month[df_month['last_month_end'].dt.month + 2 == month]
            df_month_2_not_renewed = df_month_2[df_month_2['month'].dt.month != df_month_2['last_month_end'].dt.month + 1]
            total_last_month_2 = df_month_2_not_renewed.groupby('id')['отгрузка'].sum().sum()
            df_month_2_renewed = df_month_2_not_renewed[df_month_2_not_renewed['month'].dt.month == month]
            total_renewed_month_2 = df_month_2_renewed.groupby('id')['отгрузка'].sum().sum()
            renewal_rate_month_2 = total_renewed_month_2 / total_last_month_2 if total_last_month_2 > 0 else 0

            # Сохраняем результаты.
            results.append({
                'manager': manager,
                'month': month,
                'renewal_rate_month_1': renewal_rate_month_1,
                'renewal_rate_month_2': renewal_rate_month_2
            })

    # Рассчитываем коэффициенты пролонгации за год.
    for manager in all_managers:
        # Фильтруем данные для текущего года.
        if manager == 'all':
            df_year = df[df['last_month_end'].dt.year == target_year]
        else:
            df_year = df[(df['am'] == manager) & (df['last_month_end'].dt.year == target_year)]

        # Рассчитываем коэффициент пролонгации для первого месяца.
        total_last_month_1 = df_year[df_year['month'].dt.month == df_year['last_month_end'].dt.month + 1].groupby('id')['отгрузка'].sum().sum()
        total_last_month_2 = df_year[df_year['month'].dt.month == df_year['last_month_end'].dt.month + 2].groupby('id')['отгрузка'].sum().sum()
        total_last_month = total_last_month_1 + total_last_month_2

        df_year_renewed_1 = df_year[df_year['month'].dt.month == df_year['last_month_end'].dt.month + 1]
        df_year_renewed_2 = df_year[df_year['month'].dt.month == df_year['last_month_end'].dt.month + 2]
        total_renewed_month_1 = df_year_renewed_1.groupby('id')['отгрузка'].sum().sum()
        total_renewed_month_2 = df_year_renewed_2.groupby('id')['отгрузка'].sum().sum()
        total_renewed = total_renewed_month_1 + total_renewed_month_2

        renewal_rate_year = total_renewed / total_last_month if total_last_month > 0 else 0

        # Сохраняем результаты.
        results.append({
            'manager': manager,
            'month': 'year',
            'renewal_rate_month_1': renewal_rate_year,
            'renewal_rate_month_2': 0
        })

    return pd.DataFrame(results)

# Вызываем функцию для расчета коэффициентов пролонгации
renewal_rates = calculate_renewal_rates(df)

# Выводим результат на экран
print(renewal_rates)

# Экспорт в Excel
renewal_rates.to_excel("renewal_rates.xlsx", index=False)

DateParseError: month must be in 1..12: 2023-0, at position 0