<a href="https://colab.research.google.com/github/Nikita785/BLCMods/blob/master/day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df_fd = pd.read_csv('/content/financial_data.csv')
df_pr = pd.read_csv('/content/prolongations.csv')

In [ ]:
#  Шаг первый: очистка данных

  # df_fd

#    - Удалил столбец "Причины дубля" из df_fd
df_fd = df_fd.drop('Причина дубля', axis=1)

#    - Преобразовал месяцы в df_fd в числовой тип и заполнил NaN нулями
df_fd_dt = ['id', 'Account']

for col in df_fd.columns:
  if col not in df_fd_dt:
    df_fd[col] = pd.to_numeric(df_fd[col], errors='coerce').fillna(0)

#     - Преобразовал названия столбцов с месяцами на английский

month_translation = {
    'Январь': 'January',
    'Февраль': 'February',
    'Март': 'March',
    'Апрель': 'April',
    'Май': 'May',
    'Июнь': 'June',
    'Июль': 'July',
    'Август': 'August',
    'Сентябрь': 'September',
    'Октябрь': 'October',
    'Ноябрь': 'November',
    'Декабрь': 'December'
}

for col in df_fd.columns:
    month_name_parts = col.split()
    if len(month_name_parts) > 1 and month_name_parts[0] in month_translation:
        new_col = month_translation[month_name_parts[0]] + ' ' + month_name_parts[1]
        df_fd.rename(columns={col: new_col}, inplace=True)

  # df_pr
month_translation_dr = {
    'январь': 'January',
    'февраль': 'February',
    'март': 'March',
    'апрель': 'April',
    'май': 'May',
    'июнь': 'June',
    'июль': 'July',
    'август': 'August',
    'сентябрь': 'September',
    'октябрь': 'October',
    'ноябрь': 'November',
    'декабрь': 'December'
}

#Переименовал столбцы
df_pr.rename(columns={'AM': 'Account', 'month': 'Month'}, inplace=True)

#Преобразовал значения столбца

for index, value in df_pr['Month'].items():
  value_parts = str(value).split()
  if len(value_parts) > 1 and value_parts[0].lower() in month_translation_dr:
    new_val = month_translation_dr[value_parts[0].lower()] + ' ' + value_parts[1]
    df_pr.loc[index, 'Month'] = new_val

In [ ]:
# Шаг второй: объединение таблиц для произведения расчётов


df_merge = pd.merge(df_fd, df_pr, on=['id', '', how='left')

In [ ]:
df_merge = pd.merge(df_fd, df_pr, on=['id', 'Account'], how='left')

In [ ]:
df_merge.dtype

,id,November 2022,December 2022,January 2023,February 2023,March 2023,April 2023,May 2023,June 2023,July 2023,August 2023,September 2023,October 2023,November 2023,December 2023,January 2024,February 2024,Account,Month
0,42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Васильев Артем Александрович,November 2022
1,657,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Васильев Артем Александрович,November 2022
2,657,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Васильев Артем Александрович,November 2022
3,594,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Васильев Артем Александрович,November 2022
4,665,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Васильев Артем Александрович,November 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
642,281,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Соколова Анастасия Викторовна,May 2023
643,281,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Соколова Анастасия Викторовна,December 2023
644,785,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Соколова Анастасия Викторовна,December 2023
645,913,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Смирнова Ольга Владимировна,December 2023
646,930,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Кузнецов Михаил Иванович,NaN