<a href="https://colab.research.google.com/github/Nikita785/BLCMods/blob/master/day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df_fd = pd.read_csv('/content/financial_data.csv')
df_pr = pd.read_csv('/content/prolongations.csv')

In [ ]:
df_pr

       id         month                             AM
0      42   ноябрь 2022   Васильев Артем Александрович
1     453   ноябрь 2022   Васильев Артем Александрович
2     548   ноябрь 2022      Михайлов Андрей Сергеевич
3      87   ноябрь 2022  Соколова Анастасия Викторовна
4     429   ноябрь 2022  Соколова Анастасия Викторовна
..    ...           ...                            ...
472   955  декабрь 2023    Смирнова Ольга Владимировна
473  1004  декабрь 2023                        без А/М
474   281  декабрь 2023  Соколова Анастасия Викторовна
475   785  декабрь 2023  Соколова Анастасия Викторовна
476   913  декабрь 2023    Смирнова Ольга Владимировна

[477 rows x 3 columns]

In [ ]:
df_fd

,id,Причина дубля,Ноябрь 2022,Декабрь 2022,Январь 2023,Февраль 2023,Март 2023,Апрель 2023,Май 2023,Июнь 2023,Июль 2023,Август 2023,Сентябрь 2023,Октябрь 2023,Ноябрь 2023,Декабрь 2023,Январь 2024,Февраль 2024,Account
0,42,NaN,"36 220,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
1,657,первая часть оплаты,стоп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
2,657,вторая часть оплаты,стоп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
3,594,NaN,стоп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
4,665,NaN,"10 000,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,281,основные работы,"76 550,00","79 950,00","66 900,00","89 150,00","108 450,00","77 100,00","78 800,00","126 740,00","117 730,00","115 860,00","160 770,00","142 490,00","99 125,00","74 350,00","105 775,00","92 065,00",Соколова Анастасия Викторовна
447,281,доп работы,"21 450,00","13 300,00","15 900,00","19 850,00","17 350,00","14 650,00","15 900,00","3 000,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
448,785,NaN,NaN,NaN,NaN,"5 306,60","12 898,10","5 287,00","10 180,00","8 600,00","3 860,00","8 600,00","700,00","700,00",в ноль,в ноль,NaN,NaN,Соколова Анастасия Викторовна
449,913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"58 200,00","58 200,00","58 200,00","58 200,00","58 200,00","58 200,00",NaN,NaN,Смирнова Ольга Владимировна
450,930,первая часть оплаты,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"36 687,50","31 152,50","30 350,00","34 547,50","25 750,00","25 600,00",Кузнецов Михаил Иванович

In [ ]:
#  Шаг первый: очистка данных

  # df_fd

#    - Удалил столбец "Причины дубля" из df_fd
df_fd = df_fd.drop('Причина дубля', axis=1)

#    - Преобразовал месяцы в df_fd в числовой тип и заполнил NaN нулями
df_fd_dt = ['id', 'Account']

for col in df_fd.columns:
  if col not in df_fd_dt:
    df_fd[col] = pd.to_numeric(df_fd[col], errors='coerce').fillna(0)

#     - Преобразовал названия столбцов с месяцами на английский

month_translation = {
    'Январь': 'January',
    'Февраль': 'February',
    'Март': 'March',
    'Апрель': 'April',
    'Май': 'May',
    'Июнь': 'June',
    'Июль': 'July',
    'Август': 'August',
    'Сентябрь': 'September',
    'Октябрь': 'October',
    'Ноябрь': 'November',
    'Декабрь': 'December'
}

for col in df_fd.columns:
    month_name_parts = col.split()
    if len(month_name_parts) > 1 and month_name_parts[0] in month_translation:
        new_col = month_translation[month_name_parts[0]] + ' ' + month_name_parts[1]
        df_fd.rename(columns={col: new_col}, inplace=True)

  # df_pr
month_translation_dr = {
    'январь': 'January',
    'февраль': 'February',
    'март': 'March',
    'апрель': 'April',
    'май': 'May',
    'июнь': 'June',
    'июль': 'July',
    'август': 'August',
    'сентябрь': 'September',
    'октябрь': 'October',
    'ноябрь': 'November',
    'декабрь': 'December'
}

#Переименовал столбцы
df_pr.rename(columns={'AM': 'Account', 'month': 'Month'}, inplace=True)

#Преобразовал значения столбца

for index, value in df_pr['Month'].items():
  value_parts = str(value).split()
  if len(value_parts) > 1 and value_parts[0].lower() in month_translation_dr:
    new_val = month_translation_dr[value_parts[0].lower()] + ' ' + value_parts[1]
    df_pr.loc[index, 'Month'] = new_val

In [ ]:
from datetime import datetime
# Шаг второй: объединение таблиц для произведения расчётов


df_merge = pd.merge(df_fd, df_pr, on=['id', 'Account'], how='left')
df_merge['Month'] = pd.to_datetime(df_merge['Month'], format='%B %Y')

In [ ]:
def prolongation_coef (df,
                       target_month,
                       id_column='id',
                       manager_column='Account',
                       end_month_col='Month'):

  if target_month >= pd.to_datetime('2023-01-01'):

    if isinstance(target_month, str):
      target_month = pd.to_datetime(target_month)

    prev_month = target_month - pd.DateOffset(months=1)
    prev_prev_month = target_month - pd.DateOffset(months=2)

    target_month_x = target_month.strftime('%B %Y')
    prev_month_x = prev_month.strftime('%B %Y')
    prev_prev_month_x = prev_prev_month.strftime('%B %Y')

    #Расчёт коэффицента пролонгации 1
    #  Фильтрация тех проектов,
    def first_pc(df, end_month_col, prev_month_x, target_month_x):
      end_month_col_x = end_month_col.strftime('%B %Y')
      df_prev_filtr_1 = df[df[end_month_col] == prev_month_x]
      df_prev_filtr_1_sum = df_prev_filtr_1[prev_month].sum() #знаменатель
      df_curr_filtr_1 = df[df[end_month_col] == target_month_x]
      df_curr_filter_1_sum = df_curr_filtr_1[target_month].sum() #числитель
      result = df_prev_filtr_1_sum / df_curr_filter_1_sum

id                         int64
November 2022            float64
December 2022            float64
January 2023             float64
February 2023            float64
March 2023               float64
April 2023               float64
May 2023                 float64
June 2023                float64
July 2023                float64
August 2023              float64
September 2023           float64
October 2023             float64
November 2023            float64
December 2023            float64
January 2024             float64
February 2024            float64
Account                   object
Month             datetime64[ns]
dtype: object

In [ ]:

import pandas as pd
import numpy as np

def calculate_renewal_rates_from_df(df_financial, df_prolongations=None):
    """
    Рассчитывает коэффициенты пролонгации для каждого менеджера и для всего отдела в целом
    за каждый месяц и за год.

    Args:
        df_financial (pd.DataFrame): DataFrame с финансовыми данными, содержащий столбцы:
            - 'id': id проекта
            - Месяцы в формате 'Month Name YYYY': сумма отгрузки проекта в данный месяц (например, 'January 2023')
            - 'Account': ФИО ответственного аккаунт-менеджера
            - 'Month': дата последнего месяца реализации проекта (в формате 'YYYY-MM-DD')

        df_prolongations (pd.DataFrame, optional): DataFrame с данными о пролонгациях.  Если None, будет расчитано только по df_financial.
            Должен содержать столбцы:
            - 'id': id проекта
            - 'month': последний месяц реализации проекта
            - 'AM': ФИО ответственного аккаунт-менеджера (данные первичны по отношению к df_financial)
            Defaults to None.

    Returns:
        tuple:  (monthly_renewal_rates, annual_renewal_rates)
            monthly_renewal_rates (dict): Словарь, где ключи - названия месяцев, а значения - DataFrame с коэффициентами пролонгации для каждого менеджера и для всего отдела.
            annual_renewal_rates (pd.DataFrame): DataFrame с годовыми коэффициентами пролонгации для каждого менеджера и для всего отдела.
    """

    # Предобработка данных
    df = df_financial.copy()

    # 1. Преобразование столбца 'Month' в datetime
    df['Month'] = pd.to_datetime(df['Month'], errors='coerce') #errors='coerce' чтобы NaT обрабатывать

    # 2. Проверка и исправление типов данных
    month_cols = [col for col in df.columns if isinstance(col, str) and any(month in col.lower() for month in ['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december'])]
    for col in month_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)  # Преобразуем в числовой тип, некорректные значения заменяем на 0

    # Замена NaT на None
    df = df.replace({pd.NaT: None})

    # 3. Фильтрация данных за 2023 год
    df = df[df['Month'].dt.year == 2023]

    # 4. Агрегируем данные по id и месяцу, суммируем значения, чтобы убрать дубликаты.
    df = df.groupby(['id', 'Account', 'Month'])[month_cols].sum().reset_index()

    # Если df_prolongations передан, то объединяем DataFrame.
    if df_prolongations is not None:
        # Проверка типов данных
        df_prolongations['month'] = pd.to_datetime(df_prolongations['month'])

        # Переименовываем столбец 'month' в 'prolongation_month' для ясности
        df_prolongations = df_prolongations.rename(columns={'month': 'prolongation_month'})

        # Объединяем df_financial и df_prolongations
        df = pd.merge(df, df_prolongations, left_on=['id', 'Account'], right_on=['id', 'AM'], how='left')

        # Удаляем дублирующийся столбец Account, если он есть.
        if 'Account_y' in df.columns:
            df = df.drop(columns=['Account_y'])
        df = df.rename(columns={'Account_x': 'Account'})

        df['AM'] = df['AM'].fillna(df['Account'])  # Заполняем пропуски в AM данными из Account

        # Фильтруем данные за 2023 год
        df = df[df['prolongation_month'].dt.year == 2023]

    else:
        df['AM'] = df['Account']
        df['prolongation_month'] = df['Month'] #Если нет df_prolongations то month берем из финансовых данных

    # Функция для расчета коэффициентов пролонгации
    def calculate_renewal_rates(df, target_month):
        """
        Рассчитывает коэффициенты пролонгации для заданного месяца.

        Args:
            df (pd.DataFrame): Объединенный DataFrame с данными о пролонгациях и финансах.
            target_month (pd.Timestamp): Месяц, для которого нужно рассчитать коэффициенты пролонгации.

        Returns:
            pd.DataFrame: DataFrame с коэффициентами пролонгации для каждого менеджера и для всего отдела.
        """

        # Рассчитываем начало и конец предыдущего и позапрошлого месяцев
        last_month_end = target_month - pd.DateOffset(months=1)
        last_month_start = last_month_end - pd.DateOffset(days=last_month_end.day - 1) # Первый день прошлого месяца

        previous_month_end = target_month - pd.DateOffset(months=2)
        previous_month_start = previous_month_end - pd.DateOffset(days=previous_month_end.day - 1)


        # Формируем строку месяца для поиска столбца.
        month_str = target_month.strftime('%B %Y')

        # Фильтруем данные для проектов, завершившихся в прошлом месяце
        projects_ended_last_month = df[(df['Month'] >= last_month_start) & (df['Month'] <= last_month_end)].copy()

        # Фильтруем данные для проектов, пролонгированных в первый месяц (целевой месяц)
        projects_renewed_first_month = df[(df['Month'] >= last_month_start) & (df['Month'] <= last_month_end) & (df['prolongation_month'] == target_month)].copy()

        # Фильтруем данные для проектов, завершившихся в позапрошлом месяце и НЕ пролонгированных в прошлом месяце
        projects_not_renewed_first_month = df[(df['Month'] >= previous_month_start) & (df['Month'] <= previous_month_end)].copy()
        projects_not_renewed_first_month = projects_not_renewed_first_month[~projects_not_renewed_first_month['id'].isin(projects_ended_last_month['id'].unique())]

        # Фильтруем данные для проектов, пролонгированных во второй месяц (целевой месяц)
        projects_renewed_second_month = df[(df['Month'] >= previous_month_start) & (df['Month'] <= previous_month_end) & (df['prolongation_month'] == target_month) & (df['id'].isin(projects_not_renewed_first_month['id'].unique()))].copy()

        # Функция для расчета коэффициента пролонгации
        def calculate_rate(group, ended_projects, renewed_projects, month_str):
            total_volume = ended_projects[month_str].sum() if not ended_projects.empty and month_str in ended_projects.columns else 0
            renewed_volume = renewed_projects[month_str].sum() if not renewed_projects.empty and month_str in renewed_projects.columns else 0
            rate = renewed_volume / total_volume if total_volume > 0 else 0
            return rate

        # Расчет для первого месяца
        def calculate_rate_first_month(group, month_str):
            ended_projects = projects_ended_last_month[projects_ended_last_month['AM'] == group.name]
            renewed_projects = projects_renewed_first_month[projects_renewed_first_month['AM'] == group.name]
            return calculate_rate(group, ended_projects, renewed_projects, month_str)

        # Расчет для второго месяца
        def calculate_rate_second_month(group, month_str):
            ended_projects = projects_not_renewed_first_month[projects_not_renewed_first_month['AM'] == group.name]
            renewed_projects = projects_renewed_second_month[projects_renewed_second_month['AM'] == group.name]
            return calculate_rate(group, ended_projects, renewed_projects, month_str)

        # Расчет по менеджерам для первого месяца
        renewal_rates_first_month = df.groupby('AM').apply(lambda x: calculate_rate_first_month(x, month_str)).reset_index(name='Renewal_Rate_First_Month')

        # Расчет по менеджерам для второго месяца
        renewal_rates_second_month = df.groupby('AM').apply(lambda x: calculate_rate_second_month(x, month_str)).reset_index(name='Renewal_Rate_Second_Month')

        # Расчет для всего отдела (первый месяц)
        total_ended_volume = projects_ended_last_month[month_str].sum() if not projects_ended_last_month.empty and month_str in projects_ended_last_month.columns else 0
        total_renewed_volume = projects_renewed_first_month[month_str].sum() if not projects_renewed_first_month.empty and month_str in projects_renewed_first_month.columns else 0
        overall_renewal_rate_first_month = total_renewed_volume / total_ended_volume if total_ended_volume > 0 else 0

        # Расчет для всего отдела (второй месяц)
        total_ended_volume_2 = projects_not_renewed_first_month[month_str].sum() if not projects_not_renewed_first_month.empty and month_str in projects_not_renewed_first_month.columns else 0
        total_renewed_volume_2 = projects_renewed_second_month[month_str].sum() if not projects_renewed_second_month.empty and month_str in projects_renewed_second_month.columns else 0
        overall_renewal_rate_second_month = total_renewed_volume_2 / total_ended_volume_2 if total_ended_volume_2 > 0 else 0

        # Объединяем результаты
        renewal_rates = pd.merge(renewal_rates_first_month, renewal_rates_second_month, on='AM', how='outer')

        # Добавляем строку с общим результатом по отделу
        renewal_rates = renewal_rates.append({'AM': 'Overall', 'Renewal_Rate_First_Month': overall_renewal_rate_first_month, 'Renewal_Rate_Second_Month': overall_renewal_rate_second_month}, ignore_index=True)

        return renewal_rates


    # Список месяцев для анализа (все месяцы 2023 года)
    months_2023 = pd.date_range(start='2023-01-01', end='2023-12-01', freq='MS')

    # Рассчитываем коэффициенты для каждого месяца
    monthly_renewal_rates = {}
    for month in months_2023:
        monthly_renewal_rates[month.strftime('%B')] = calculate_renewal_rates(df.copy(), month)


    # Годовой расчет (агрегируем месячные данные)
    def calculate_annual_renewal_rates(monthly_renewal_rates):
        """
        Рассчитывает годовые коэффициенты пролонгации на основе месячных данных.

        Args:
            monthly_renewal_rates (dict): Словарь, где ключи - названия месяцев, а значения - DataFrame с месячными коэффициентами.

        Returns:
            pd.DataFrame: DataFrame с годовыми коэффициентами пролонгации для каждого менеджера и для всего отдела.
        """
        annual_data = {}
        for month, rates in monthly_renewal_rates.items():
            for _, row in rates.iterrows():
                am = row['AM']
                if am not in annual_data:
                    annual_data[am] = {'AM': am, 'Total_First_Month_Volume': 0, 'Total_First_Month_Renewed': 0, 'Total_Second_Month_Volume': 0, 'Total_Second_Month_Renewed': 0}

                # Получаем данные для расчета
                target_month = pd.to_datetime(month, format='%B').replace(year=2023)
                month_str = target_month.strftime('%B %Y')

                # Рассчитываем начало и конец предыдущего и позапрошлого месяцев
                last_month_end = target_month - pd.DateOffset(months=1)
                last_month_start = last_month_end - pd.DateOffset(days=last_month_end.day - 1) # Первый день прошлого месяца

                previous_month_end = target_month - pd.DateOffset(months=2)
                previous_month_start = previous_month_end - pd.DateOffset(days=previous_month_end.day - 1)

                # Фильтруем данные для проектов, завершившихся в прошлом месяце
                projects_ended_last_month = df[(df['Month'] >= last_month_start) & (df['Month'] <= last_month_end) & (df['AM'] == am)].copy()

                # Фильтруем данные для проектов, пролонгированных в первый месяц (целевой месяц)
                projects_renewed_first_month = df[(df['Month'] >= last_month_start) & (df['Month'] <= last_month_end) & (df['prolongation_month'] == target_month) & (df['AM'] == am)].copy()

                # Фильтруем данные для проектов, завершившихся в позапрошлом месяце и НЕ пролонгированных в прошлом месяце
                projects_not_renewed_first_month = df[(df['Month'] >= previous_month_start) & (df['Month'] <= previous_month_end) & (df['AM'] == am)].copy()
                projects_not_renewed_first_month = projects_not_renewed_first_month[~projects_not_renewed_first_month['id'].isin(projects_ended_last_month['id'].unique())]

                # Фильтруем данные для проектов, пролонгированных во второй месяц (целевой месяц)
                projects_renewed_second_month = df[(df['Month'] >= previous_month_start) & (df['Month'] <= previous_month_end) & (df['prolongation_month'] == target_month) & (df['id'].isin(projects_not_renewed_first_month['id'].unique()))  & (df['AM'] == am)].copy()


                annual_data[am]['Total_First_Month_Volume'] += projects_ended_last_month[month_str].sum() if not projects_ended_last_month.empty and month_str in projects_ended_last_month.columns else 0
                annual_data[am]['Total_First_Month_Renewed'] += projects_renewed_first_month[month_str].sum() if not projects_renewed_first_month.empty and month_str in projects_renewed_first_month.columns else 0
                annual_data[am]['Total_Second_Month_Volume'] += projects_not_renewed_first_month[month_str].sum() if not projects_not_renewed_first_month.empty and month_str in projects_not_renewed_first_month.columns else 0
                annual_data[am]['Total_Second_Month_Renewed'] += projects_renewed_second_month[month_str].sum() if not projects_renewed_second_month.empty and month_str in projects_renewed_second_month.columns else 0

        # Преобразуем в DataFrame
        annual_df = pd.DataFrame.from_dict(annual_data, orient='index')

        # Рассчитываем коэффициенты
        annual_df['Annual_Renewal_Rate_First_Month'] = annual_df['Total_First_Month_Renewed'] / annual_df['Total_First_Month_Volume']
        annual_df['Annual_Renewal_Rate_Second_Month'] = annual_df['Total_Second_Month_Renewed'] / annual_df['Total_Second_Month_Volume']

        # Выбираем нужные столбцы
        annual_df = annual_df[['AM', 'Annual_Renewal_Rate_First_Month', 'Annual_Renewal_Rate_Second_Month']]

        return annual_df

    # Рассчитываем годовые коэффициенты
    annual_renewal_rates = calculate_annual_renewal_rates(monthly_renewal_rates)

    return monthly_renewal_rates, annual_renewal_rates

# Пример использования:
# (monthly_renewal_rates, annual_renewal_rates) = calculate_renewal_rates_from_df(df_financial, df_prolongations)