<a href="https://colab.research.google.com/github/Nikita785/BLCMods/blob/master/day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd

df_fd = pd.read_csv('/content/financial_data.csv')
df_pr = pd.read_csv('/content/prolongations.csv')

In [25]:
df_pr.rename(columns={'AM' : 'Account'}, inplace=True)

In [27]:
df_merged = pd.merge(df_fd, df_pr, on=['id', 'Account'], how='inner')

In [30]:
# Обработка и работа с дублями

'''
Всего у нас 7 уникальных значений в этом столбце.

1. NaN - обработка как обычных проектов и в случае, если встречается "стоп" или "end" - исключить из расчётов
2. + 3. Первая часть оплаты + вторая часть оплаты - суммируем значения по id проектов
4. Изменение ЮЛ - если нет стоп/end - то считаем как начало нового проекта, а если есть, то исключить проект
5. 6. Доп. работы и основные работа - обрабатывать как разные типы задач и разные проекты
7. карты, банки - cуммировать как обычный проект
'''

def duble_func

In [37]:
df_merged[df_merged['Причина дубля'] == 'карты, банки']

,id,Причина дубля,Ноябрь 2022,Декабрь 2022,Январь 2023,Февраль 2023,Март 2023,Апрель 2023,Май 2023,Июнь 2023,Июль 2023,Август 2023,Сентябрь 2023,Октябрь 2023,Ноябрь 2023,Декабрь 2023,Январь 2024,Февраль 2024,Account,month
604,228,"карты, банки","28 200,00","28 200,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","43 400,00","43 400,00",Васильев Артем Александрович,декабрь 2022
605,228,"карты, банки","28 200,00","28 200,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","33 885,00","43 400,00","43 400,00",Васильев Артем Александрович,декабрь 2023

In [5]:
df_fd['Причина дубля'].unique()

array([nan, 'первая часть оплаты', 'вторая часть оплаты', 'изменение ЮЛ',
       'доп работы', 'основные работы', 'карты, банки'], dtype=object)

In [ ]:
df_pr

       id         month                             AM
0      42   ноябрь 2022   Васильев Артем Александрович
1     453   ноябрь 2022   Васильев Артем Александрович
2     548   ноябрь 2022      Михайлов Андрей Сергеевич
3      87   ноябрь 2022  Соколова Анастасия Викторовна
4     429   ноябрь 2022  Соколова Анастасия Викторовна
..    ...           ...                            ...
472   955  декабрь 2023    Смирнова Ольга Владимировна
473  1004  декабрь 2023                        без А/М
474   281  декабрь 2023  Соколова Анастасия Викторовна
475   785  декабрь 2023  Соколова Анастасия Викторовна
476   913  декабрь 2023    Смирнова Ольга Владимировна

[477 rows x 3 columns]

In [ ]:
#  Шаг первый: очистка данных

  # df_fd

#    - Удалил столбец "Причины дубля" из df_fd
df_fd = df_fd.drop('Причина дубля', axis=1)

#    - Преобразовал месяцы в df_fd в числовой тип и заполнил NaN нулями
df_fd_dt = ['id', 'Account']

for col in df_fd.columns:
  if col not in df_fd_dt:
    df_fd[col] = pd.to_numeric(df_fd[col], errors='coerce').fillna(0)

#     - Преобразовал названия столбцов с месяцами на английский

month_translation = {
    'Январь': 'January',
    'Февраль': 'February',
    'Март': 'March',
    'Апрель': 'April',
    'Май': 'May',
    'Июнь': 'June',
    'Июль': 'July',
    'Август': 'August',
    'Сентябрь': 'September',
    'Октябрь': 'October',
    'Ноябрь': 'November',
    'Декабрь': 'December'
}

for col in df_fd.columns:
    month_name_parts = col.split()
    if len(month_name_parts) > 1 and month_name_parts[0] in month_translation:
        new_col = month_translation[month_name_parts[0]] + ' ' + month_name_parts[1]
        df_fd.rename(columns={col: new_col}, inplace=True)

  # df_pr
month_translation_dr = {
    'январь': 'January',
    'февраль': 'February',
    'март': 'March',
    'апрель': 'April',
    'май': 'May',
    'июнь': 'June',
    'июль': 'July',
    'август': 'August',
    'сентябрь': 'September',
    'октябрь': 'October',
    'ноябрь': 'November',
    'декабрь': 'December'
}

#Переименовал столбцы
df_pr.rename(columns={'AM': 'Account', 'month': 'Month'}, inplace=True)

#Преобразовал значения столбца

for index, value in df_pr['Month'].items():
  value_parts = str(value).split()
  if len(value_parts) > 1 and value_parts[0].lower() in month_translation_dr:
    new_val = month_translation_dr[value_parts[0].lower()] + ' ' + value_parts[1]
    df_pr.loc[index, 'Month'] = new_val

In [ ]:
from datetime import datetime
# Шаг второй: объединение таблиц для произведения расчётов


df_merge = pd.merge(df_fd, df_pr, on=['id', 'Account'], how='left')
df_merge['Month'] = pd.to_datetime(df_merge['Month'], format='%B %Y')

In [ ]:
def prolongation_coef (df,
                       target_month,
                       id_column='id',
                       manager_column='Account',
                       end_month_col='Month'):

  if target_month >= pd.to_datetime('2023-01-01'):

    if isinstance(target_month, str):
      target_month = pd.to_datetime(target_month)

    prev_month = target_month - pd.DateOffset(months=1)
    prev_prev_month = target_month - pd.DateOffset(months=2)

    target_month_x = target_month.strftime('%B %Y')
    prev_month_x = prev_month.strftime('%B %Y')
    prev_prev_month_x = prev_prev_month.strftime('%B %Y')

    #Расчёт коэффицента пролонгации 1

    '''
      K1 = O1 / Op, где

      O1 - сумма отгрузки проектов, которые были пролонгированы в первый месяц после завершения
        (т.е. проекты были завершены в прошлом месяце и продолжили работу в первом месяце)
      Op - сумма отгрузки последнего месяца реализации всех завершившихся в прошлом месяце проектов
    '''


    #  Фильтрация тех проектов,
    def first_pc(df, end_month_col, prev_month_x, target_month_x):
      end_month_col_x = end_month_col.strftime('%B %Y')
      df_prev_filtr_1 = df[df[end_month_col] == prev_month_x]
      df_prev_filtr_1_sum = df_prev_filtr_1[prev_month].sum() #знаменатель
      df_curr_filtr_1 = df[df[end_month_col] == target_month_x]
      df_curr_filter_1_sum = df_curr_filtr_1[target_month].sum() #числитель
      result = df_prev_filtr_1_sum / df_curr_filter_1_sum

id                         int64
November 2022            float64
December 2022            float64
January 2023             float64
February 2023            float64
March 2023               float64
April 2023               float64
May 2023                 float64
June 2023                float64
July 2023                float64
August 2023              float64
September 2023           float64
October 2023             float64
November 2023            float64
December 2023            float64
January 2024             float64
February 2024            float64
Account                   object
Month             datetime64[ns]
dtype: object